### ISSUE TITLE
Reproduce the results on Wild6D dataset

### ISSUE THREAD

**Issue by Michaelswitch** [CVMI-Lab/IST-Net#1]
Hi, thanks for releasing the great work. How to reproduce the 6D pose estimation results on Wild6D? Can you release the test code of Wild6D and publish the accuracy of each object category on Wild6D? It will help us a lot. Thank you very much.

**Comment by Eddieeee-Liu** [comment]
Hi, Michael! Thanks for interest, we will prepare the code for Wild6D as soon as possible
