### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: '/media/jian/ourdata/LHT/IST-NET/IST-Net-main/data/obj_models/camera_train.pkl'

### ISSUE THREAD

**Issue by SHN7x** [CVMI-Lab/IST-Net#2]
Where is the address  obj_models/camera_train.pkl'

**Comment by Eddieeee-Liu** [comment]
This problem seems that you didn't put the data to the path "/media/jian/ourdata/LHT/IST-NET/IST-Net-main/data/", you can solve this problem by using soft link
