### ISSUE TITLE
分兩階段訓練時出錯

### ISSUE THREAD

**Issue by corpse-dog** [CVMI-Lab/IST-Net#4]
在ist_net_freeze_world_enhancer.yaml中加入了第一階段的訓練權重：
model_arch: ist_net
freeze_world_enhancer: True
world_enhancer_weights: /data/jhq/IST-Net/log/posenet_gt_default/epoch_30.pth      # [Path to we weights]

開啟第二階段的訓練時報如下錯誤：
RuntimeError: Error(s) in loading state_dict for DataParallel:
        Missing key(s) in state_dict: "module.rgb_cam_extractor.model.feats.conv1.weight", "module.rgb_cam_extractor.model.feats.bn1.weight", "module.rgb_cam_extractor.model.feats.bn1.bias", "module.rgb_cam_extractor.model.feats.bn1.running_mean", "module.rgb_cam_extractor.model.feats.bn1.running_var", "module.rgb_cam_extractor.model.feats.layer1.0.conv1.weight", "module.rgb_cam_extractor.model.feats.layer1.0.bn1.weight", "module.rgb_cam_extractor.model.feats.layer1.0.bn1.bias", "module.rgb_cam_extractor.model.feats.layer1.0.bn1.running_mean", "module.rgb_cam_extractor.model.feats.layer1.0.bn1.running_var", "module.rgb_cam_extractor.model.feats.layer1.0.conv2.weight", "module.rgb_cam_extractor.model.feats.layer1.0.bn2.weight", "module.rgb_cam_extractor.model.feats.layer1.0.bn2.bias", "module.rgb_cam_extractor.model.feats.layer1.0.bn2.running_mean", "module.rgb_cam_extractor.model.feats.layer1.0.bn2.running_var", "module.rgb_cam_extractor.model.feats.layer1.1.conv1.weight", "module.rgb_cam_extractor.model.feats.layer1.1.bn1.weight", "module.rgb_cam_extractor.model.feats.layer1.1.bn1.bias", "module.rgb_cam_extractor.model.feats.layer1.1.bn1.running_mean", "module.rgb_cam_extractor.model.feats.layer1.1.bn1.running_var", "module.rgb_cam_extractor.model.feats.layer1.1.conv2.weight", "module.rgb_cam_extractor.model.feats.layer1.1.bn2.weight", "module.rgb_cam_extractor.model.feats.layer1.1.bn2.bias", "module.rgb_cam_extractor.model.feats.layer1.1.bn2.running_mean", "module.rgb_cam_extractor.model.feats.layer1.1.bn2.running_var", "module.rgb_cam_extractor.model.feats.layer2.0.conv1.weight", "module.rgb_cam_extractor.model.feats.layer2.0.bn1.weight", "module.rgb_cam_extractor.model.feats.layer2.0.bn1.bias", "module.rgb_cam_extractor.model.feats.layer2.0.bn1.running_mean", "module.rgb_cam_extractor.model.feats.layer2.0.bn1.running_var", "module.rgb_cam_extractor.model.feats.layer2.0.conv2.weight", "module.rgb_cam_extractor.model.feats.layer2.0.bn2.weight", "module.rgb_cam_extractor.model.feats.layer2.0.bn2.bias", "module.rgb_cam_extractor.model.feats.layer2.0.bn2.running_mean", "module.rgb_cam_extractor.model.feats.layer2.0.bn2.running_var", "module.rgb_cam_extractor.model.feats.layer2.0.downsample.0.weight", "module.rgb_cam_extractor.model.feats.layer2.0.downsample.1.weight", "module.rgb_cam_extractor.model.feats.layer2.0.downsample.1.bias", "module.rgb_cam_extractor.model.feats.layer2.0.downsample.1.running_mean", "module.rgb_cam_extractor.model.feats.layer2.0.downsample.1.running_var", "module.rgb_cam_extractor.model.feats.layer2.1.conv1.weight", "module.rgb_cam_extractor.model.feats.layer2.1.bn1.weight", "module.rgb_cam_extractor.model.feats.layer2.1.bn1.bias", "module.rgb_cam_extractor.model.feats.layer2.1.bn1.running_mean", "module.rgb_cam_extractor.model.feats.layer2.1.bn1.running_var", "module.rgb_cam_extractor.model.feats.layer2.1.conv2.weight", "module.rgb_cam_extractor.model.feats.layer2.1.bn2.weight", "module.rgb_cam_extractor.model.feats.layer2.1.bn2.bias", "module.rgb_cam_extractor.model.feats.layer2.1.bn2.running_mean", "module.rgb_cam_extractor.model.feats.layer2.1.bn2.running_var", "module.rgb_cam_extractor.model.feats.layer3.0.conv1.weight", "module.rgb_cam_extractor.model.feats.layer3.0.bn1.weight", "module.rgb_cam_extractor.model.feats.layer3.0.bn1.bias", "module.rgb_cam_extractor.model.feats.layer3.0.bn1.running_mean", "module.rgb_cam_extractor.model.feats.layer3.0.bn1.running_var", "module.rgb_cam_extractor.model.feats.layer3.0.conv2.weight", "module.rgb_cam_extractor.model.feats.layer3.0.bn2.weight", "module.rgb_cam_extractor.model.feats.layer3.0.bn2.bias", "module.rgb_cam_extractor.model.feats.layer3.0.bn2.running_mean", "module.rgb_cam_extractor.model.feats.layer3.0.bn2.running_var", "module.rgb_cam_extractor.model.feats.layer3.0.downsample.0.weight", "module.rgb_cam_extractor.model.feats.layer3.0.downsample.1.weight", "module.rgb_cam_extractor.model.feats.layer3.0.downsample.1.bias", "module.rgb_cam_extractor.model.feats.layer3.0.downsample.1.running_mean", "module.rgb_cam_extractor.model.feats.layer3.0.downsample.1.running_var", "module.rgb_cam_extractor.model.feats.layer3.1.conv1.weight", "module.rgb_cam_extractor.model.feats.layer3.1.bn1.weight", "module.rgb_cam_extractor.model.feats.layer3.1.bn1.bias", "module.rgb_cam_extractor.model.feats.layer3.1.bn1.running_mean", "module.rgb_cam_extractor.model.feats.layer3.1.bn1.running_var", "module.rgb_cam_extractor.model.feats.layer3.1.conv2.weight", "module.rgb_cam_extractor.model.feats.layer3.1.bn2.weight", "module.rgb_cam_extractor.model.feats.layer3.1.bn2.bias", "module.rgb_cam_extractor.model.feats.layer3.1.bn2.running_mean", "module.rgb_cam_extractor.model.feats.layer3.1.bn2.running_var", "module.rgb_cam_extractor.model.feats.layer4.0.conv1.weight", "module.rgb_cam_extractor.model.feats.layer4.0.bn1.weight", "module.rgb_cam_extractor.model.feats.layer4.0.bn1.bias", "module.rgb_cam_extractor.model.feats.layer4.0.bn1.running_mean", "module.rgb_cam_extractor.model.feats.layer4.0.bn1.running_var", "module.rgb_cam_extractor.model.feats.layer4.0.conv2.weight", "module.rgb_cam_extractor.model.feats.layer4.0.bn2.weight", "module.rgb_cam_extractor.model.feats.layer4.0.bn2.bias", "module.rgb_cam_extractor.model.feats.layer4.0.bn2.running_mean", "module.rgb_cam_extractor.model.feats.layer4.0.bn2.running_var", "module.rgb_cam_extractor.model.feats.layer4.0.downsample.0.weight", "module.rgb_cam_extractor.model.feats.layer4.0.downsample.1.weight", "module.rgb_cam_extractor.model.feats.layer4.0.downsample.1.bias", "module.rgb_cam_extractor.model.feats.layer4.0.downsample.1.running_mean", "module.rgb_cam_extractor.model.feats.layer4.0.downsample.1.running_var", "module.rgb_cam_extractor.model.feats.layer4.1.conv1.weight", "module.rgb_cam_extractor.model.feats.layer4.1.bn1.weight", "module.rgb_cam_extractor.model.feats.layer4.1.bn1.bias", "module.rgb_cam_extractor.model.feats.layer4.1.bn1.running_mean", "module.rgb_cam_extractor.model.feats.layer4.1.bn1.running_var", "module.rgb_cam_extractor.model.feats.layer4.1.conv2.weight", "module.rgb_cam_extractor.model.feats.layer4.1.bn2.weight", "module.rgb_cam_extractor.model.feats.layer4.1.bn2.bias", "module.rgb_cam_extractor.model.feats.layer4.1.bn2.running_mean", "module.rgb_cam_extractor.model.feats.layer4.1.bn2.running_var", "module.rgb_cam_extractor.model.feats.fc.weight", "module.rgb_cam_extractor.model.feats.fc.bias", "module.rgb_cam_extractor.model.psp.stages.0.1.weight", "module.rgb_cam_extractor.model.psp.stages.1.1.weight", "module.rgb_cam_extractor.model.psp.stages.2.1.weight", "module.rgb_cam_extractor.model.psp.stages.3.1.weight", "module.rgb_cam_extractor.model.psp.bottleneck.weight", "module.rgb_cam_extractor.model.psp.bottleneck.bias", "module.rgb_cam_extractor.model.up_1.conv.1.weight", "module.rgb_cam_extractor.model.up_1.conv.1.bias", "module.rgb_cam_extractor.model.up_1.conv.2.weight", "module.rgb_cam_extractor.model.up_1.conv.2.bias", "module.rgb_cam_extractor.model.up_1.conv.2.running_mean", "module.rgb_cam_extractor.model.up_1.conv.2.running_var", "module.rgb_cam_extractor.model.up_1.conv.3.weight", "module.rgb_cam_extractor.model.up_2.conv.1.weight", "module.rgb_cam_extractor.model.up_2.conv.1.bias", "module.rgb_cam_extractor.model.up_2.conv.2.weight", "module.rgb_cam_extractor.model.up_2.conv.2.bias", "module.rgb_cam_extractor.model.up_2.conv.2.running_mean", "module.rgb_cam_extractor.model.up_2.conv.2.running_var", "module.rgb_cam_extractor.model.up_2.conv.3.weight", "module.rgb_cam_extractor.model.up_3.conv.1.weight", "module.rgb_cam_extractor.model.up_3.conv.1.bias", "module.rgb_cam_extractor.model.up_3.conv.2.weight", "module.rgb_cam_extractor.model.up_3.conv.2.bias", "module.rgb_cam_extractor.model.up_3.conv.2.running_mean", "module.rgb_cam_extractor.model.up_3.conv.2.running_var", "module.rgb_cam_extractor.model.up_3.conv.3.weight", "module.rgb_cam_extractor.model.final.0.weight", "module.rgb_cam_extractor.model.final.0.bias", "module.rgb_cam_extractor.model.final.1.weight", "module.rgb_cam_extractor.model.final.1.bias", "module.rgb_cam_extractor.model.final.1.running_mean", "module.rgb_cam_extractor.model.final.1.running_var", "module.rgb_cam_extractor.model.final.2.weight", "module.pts_cam_extractor.SA_modules.0.mlps.0.layer0.conv.weight", "module.pts_cam_extractor.SA_modules.0.mlps.0.layer0.normlayer.bn.weight", "module.pts_cam_extractor.SA_modules.0.mlps.0.layer0.normlayer.bn.bias", "module.pts_cam_extractor.SA_modules.0.mlps.0.layer0.normlayer.bn.running_mean", "module.pts_cam_extractor.SA_modules.0.mlps.0.layer0.normlayer.bn.running_var", "module.pts_cam_extractor.SA_modules.0.mlps.0.layer1.conv.weight", "module.pts_cam_extractor.SA_modules.0.mlps.0.layer1.normlayer.bn.weight", "module.pts_cam_extractor.SA_modules.0.mlps.0.layer1.normlayer.bn.bias", "module.pts_cam_extractor.SA_modules.0.mlps.0.layer1.normlayer.bn.running_mean", "module.pts_cam_extractor.SA_modules.0.mlps.0.layer1.normlayer.bn.running_var", "module.pts_cam_extractor.SA_modules.0.mlps.0.layer2.conv.weight", "module.pts_cam_extractor.SA_modules.0.mlps.0.layer2.normlayer.bn.weight", "module.pts_cam_extractor.SA_modules.0.mlps.0.layer2.normlayer.bn.bias", "module.pts_cam_extractor.SA_modules.0.mlps.0.layer2.normlayer.bn.running_mean", "module.pts_cam_extractor.SA_modules.0.mlps.0.layer2.normlayer.bn.running_var", "module.pts_cam_extractor.SA_modules.0.mlps.1.layer0.conv.weight", "module.pts_cam_extractor.SA_modules.0.mlps.1.layer0.normlayer.bn.weight", "module.pts_cam_extractor.SA_modules.0.mlps.1.layer0.normlayer.bn.bias", "module.pts_cam_extractor.SA_modules.0.mlps.1.layer0.normlayer.bn.running_mean", "module.pts_cam_extractor.SA_modules.0.mlps.1.layer0.normlayer.bn.running_var", "module.pts_cam_extractor.SA_modules.0.mlps.1.layer1.conv.weight", "module.pts_cam_extractor.SA_modules.0.mlps.1.layer1.normlayer.bn.weight", "module.pts_cam_extractor.SA_modules.0.mlps.1.layer1.normlayer.bn.bias", "module.pts_cam_extractor.SA_modules.0.mlps.1.layer1.normlayer.bn.running_mean", "module.pts_cam_extractor.SA_modules.0.mlps.1.layer1.normlayer.bn.running_var", "module.pts_cam_extractor.SA_modules.0.mlps.1.layer2.conv.weight", "module.pts_cam_extractor.SA_modules.0.mlps.1.layer2.normlayer.bn.weight", "module.pts_cam_extractor.SA_modules.0.mlps.1.layer2.normlayer.bn.bias", "module.pts_cam_extractor.SA_modules.0.mlps.1.layer2.normlayer.bn.running_mean", "module.pts_cam_extractor.SA_modules.0.mlps.1.layer2.normlayer.bn.running_var", "module.pts_cam_extractor.SA_modules.1.mlps.0.layer0.conv.weight", "module.pts_cam_extractor.SA_modules.1.mlps.0.layer0.normlayer.bn.weight", "module.pts_cam_extractor.SA_modules.1.mlps.0.layer0.normlayer.bn.bias", "module.pts_cam_extractor.SA_modules.1.mlps.0.layer0.normlayer.bn.running_mean", "module.pts_cam_extractor.SA_modules.1.mlps.0.layer0.normlayer.bn.running_var", "module.pts_cam_extractor.SA_modules.1.mlps.0.layer1.conv.weight", "module.pts_cam_extractor.SA_modules.1.mlps.0.layer1.normlayer.bn.weight", "module.pts_cam_extractor.SA_modules.1.mlps.0.layer1.normlayer.bn.bias", "module.pts_cam_extractor.SA_modules.1.mlps.0.layer1.normlayer.bn.running_mean", "module.pts_cam_extractor.SA_modules.1.mlps.0.layer1.normlayer.bn.running_var", "module.pts_cam_extractor.SA_modules.1.mlps.0.layer2.conv.weight", "module.pts_cam_extractor.SA_modules.1.mlps.0.layer2.normlayer.bn.weight", "module.pts_cam_extractor.SA_modules.1.mlps.0.layer2.normlayer.bn.bias", "module.pts_cam_extractor.SA_modules.1.mlps.0.layer2.normlayer.bn.running_mean", "module.pts_cam_extractor.SA_modules.1.mlps.0.layer2.normlayer.bn.running_var", "module.pts_cam_extractor.SA_modules.1.mlps.1.layer0.conv.weight", "module.pts_cam_extractor.SA_modules.1.mlps.1.layer0.normlayer.bn.weight", "module.pts_cam_extractor.SA_modules.1.mlps.1.layer0.normlayer.bn.bias", "module.pts_cam_extractor.SA_modules.1.mlps.1.layer0.normlayer.bn.running_mean", "module.pts_cam_extractor.SA_modules.1.mlps.1.layer0.normlayer.bn.running_var", "module.pts_cam_extractor.SA_modules.1.mlps.1.layer1.conv.weight", "module.pts_cam_extractor.SA_modules.1.mlps.1.layer1.normlayer.bn.weight", "module.pts_cam_extractor.SA_modules.1.mlps.1.layer1.normlayer.bn.bias", "module.pts_cam_extractor.SA_modules.1.mlps.1.layer1.normlayer.bn.running_mean", "module.pts_cam_extractor.SA_modules.1.mlps.1.layer1.normlayer.bn.running_var", "module.pts_cam_extractor.SA_modules.1.mlps.1.layer2.conv.weight", "module.pts_cam_extractor.SA_modules.1.mlps.1.layer2.normlayer.bn.weight", "module.pts_cam_extractor.SA_modules.1.mlps.1.layer2.normlayer.bn.bias", "module.pts_cam_extractor.SA_modules.1.mlps.1.layer2.normlayer.bn.running_mean", "module.pts_cam_extractor.SA_modules.1.mlps.1.layer2.normlayer.bn.running_var", "module.pts_cam_extractor.SA_modules.2.mlps.0.layer0.conv.weight", "module.pts_cam_extractor.SA_modules.2.mlps.0.layer0.normlayer.bn.weight", "module.pts_cam_extractor.SA_modules.2.mlps.0.layer0.normlayer.bn.bias", "module.pts_cam_extractor.SA_modules.2.mlps.0.layer0.normlayer.bn.running_mean", "module.pts_cam_extractor.SA_modules.2.mlps.0.layer0.normlayer.bn.running_var", "module.pts_cam_extractor.SA_modules.2.mlps.0.layer1.conv.weight", "module.pts_cam_extractor.SA_modules.2.mlps.0.layer1.normlayer.bn.weight", "module.pts_cam_extractor.SA_modules.2.mlps.0.layer1.normlayer.bn.bias", "module.pts_cam_extractor.SA_modules.2.mlps.0.layer1.normlayer.bn.running_mean", "module.pts_cam_extractor.SA_modules.2.mlps.0.layer1.normlayer.bn.running_var", "module.pts_cam_extractor.SA_modules.2.mlps.0.layer2.conv.weight", "module.pts_cam_extractor.SA_modules.2.mlps.0.layer2.normlayer.bn.weight", "module.pts_cam_extractor.SA_modules.2.mlps.0.layer2.normlayer.bn.bias", "module.pts_cam_extractor.SA_modules.2.mlps.0.layer2.normlayer.bn.running_mean", "module.pts_cam_extractor.SA_modules.2.mlps.0.layer2.normlayer.bn.running_var", "module.pts_cam_extractor.SA_modules.2.mlps.1.layer0.conv.weight", "module.pts_cam_extractor.SA_modules.2.mlps.1.layer0.normlayer.bn.weight", "module.pts_cam_extractor.SA_modules.2.mlps.1.layer0.normlayer.bn.bias", "module.pts_cam_extractor.SA_modules.2.mlps.1.layer0.normlayer.bn.running_mean", "module.pts_cam_extractor.SA_modules.2.mlps.1.layer0.normlayer.bn.running_var", "module.pts_cam_extractor.SA_modules.2.mlps.1.layer1.conv.weight", "module.pts_cam_extractor.SA_modules.2.mlps.1.layer1.normlayer.bn.weight", "module.pts_cam_extractor.SA_modules.2.mlps.1.layer1.normlayer.bn.bias", "module.pts_cam_extractor.SA_modules.2.mlps.1.layer1.normlayer.bn.running_mean", "module.pts_cam_extractor.SA_modules.2.mlps.1.layer1.normlayer.bn.running_var", "module.pts_cam_extractor.SA_modules.2.mlps.1.layer2.conv.weight", "module.pts_cam_extractor.SA_modules.2.mlps.1.layer2.normlayer.bn.weight", "module.pts_cam_extractor.SA_modules.2.mlps.1.layer2.normlayer.bn.bias", "module.pts_cam_extractor.SA_modules.2.mlps.1.layer2.normlayer.bn.running_mean", "module.pts_cam_extractor.SA_modules.2.mlps.1.layer2.normlayer.bn.running_var", "module.pts_cam_extractor.SA_modules.3.mlps.0.layer0.conv.weight", "module.pts_cam_extractor.SA_modules.3.mlps.0.layer0.normlayer.bn.weight", "module.pts_cam_extractor.SA_modules.3.mlps.0.layer0.normlayer.bn.bias", "module.pts_cam_extractor.SA_modules.3.mlps.0.layer0.normlayer.bn.running_mean", "module.pts_cam_extractor.SA_modules.3.mlps.0.layer0.normlayer.bn.running_var", "module.pts_cam_extractor.SA_modules.3.mlps.0.layer1.conv.weight", "module.pts_cam_extractor.SA_modules.3.mlps.0.layer1.normlayer.bn.weight", "module.pts_cam_extractor.SA_modules.3.mlps.0.layer1.normlayer.bn.bias", "module.pts_cam_extractor.SA_modules.3.mlps.0.layer1.normlayer.bn.running_mean", "module.pts_cam_extractor.SA_modules.3.mlps.0.layer1.normlayer.bn.running_var", "module.pts_cam_extractor.SA_modules.3.mlps.0.layer2.conv.weight", "module.pts_cam_extractor.SA_modules.3.mlps.0.layer2.normlayer.bn.weight", "module.pts_cam_extractor.SA_modules.3.mlps.0.layer2.normlayer.bn.bias", "module.pts_cam_extractor.SA_modules.3.mlps.0.layer2.normlayer.bn.running_mean", "module.pts_cam_extractor.SA_modules.3.mlps.0.layer2.normlayer.bn.running_var", "module.pts_cam_extractor.SA_modules.3.mlps.1.layer0.conv.weight", "module.pts_cam_extractor.SA_modules.3.mlps.1.layer0.normlayer.bn.weight", "module.pts_cam_extractor.SA_modules.3.mlps.1.layer0.normlayer.bn.bias", "module.pts_cam_extractor.SA_modules.3.mlps.1.layer0.normlayer.bn.running_mean", "module.pts_cam_extractor.SA_modules.3.mlps.1.layer0.normlayer.bn.running_var", "module.pts_cam_extractor.SA_modules.3.mlps.1.layer1.conv.weight", "module.pts_cam_extractor.SA_modules.3.mlps.1.layer1.normlayer.bn.weight", "module.pts_cam_extractor.SA_modules.3.mlps.1.layer1.normlayer.bn.bias", "module.pts_cam_extractor.SA_modules.3.mlps.1.layer1.normlayer.bn.running_mean", "module.pts_cam_extractor.SA_modules.3.mlps.1.layer1.normlayer.bn.running_var", "module.pts_cam_extractor.SA_modules.3.mlps.1.layer2.conv.weight", "module.pts_cam_extractor.SA_modules.3.mlps.1.layer2.normlayer.bn.weight", "module.pts_cam_extractor.SA_modules.3.mlps.1.layer2.normlayer.bn.bias", "module.pts_cam_extractor.SA_modules.3.mlps.1.layer2.normlayer.bn.running_mean", "module.pts_cam_extractor.SA_modules.3.mlps.1.layer2.normlayer.bn.running_var", "module.pts_cam_extractor.FP_modules.0.mlp.layer0.conv.weight", "module.pts_cam_extractor.FP_modules.0.mlp.layer0.normlayer.bn.weight", "module.pts_cam_extractor.FP_modules.0.mlp.layer0.normlayer.bn.bias", "module.pts_cam_extractor.FP_modules.0.mlp.layer0.normlayer.bn.running_mean", "module.pts_cam_extractor.FP_modules.0.mlp.layer0.normlayer.bn.running_var", "module.pts_cam_extractor.FP_modules.0.mlp.layer1.conv.weight", "module.pts_cam_extractor.FP_modules.0.mlp.layer1.normlayer.bn.weight", "module.pts_cam_extractor.FP_modules.0.mlp.layer1.normlayer.bn.bias", "module.pts_cam_extractor.FP_modules.0.mlp.layer1.normlayer.bn.running_mean", "module.pts_cam_extractor.FP_modules.0.mlp.layer1.normlayer.bn.running_var", "module.pts_cam_extractor.FP_modules.1.mlp.layer0.conv.weight", "module.pts_cam_extractor.FP_modules.1.mlp.layer0.normlayer.bn.weight", "module.pts_cam_extractor.FP_modules.1.mlp.layer0.normlayer.bn.bias", "module.pts_cam_extractor.FP_modules.1.mlp.layer0.normlayer.bn.running_mean", "module.pts_cam_extractor.FP_modules.1.mlp.layer0.normlayer.bn.running_var", "module.pts_cam_extractor.FP_modules.1.mlp.layer1.conv.weight", "module.pts_cam_extractor.FP_modules.1.mlp.layer1.normlayer.bn.weight", "module.pts_cam_extractor.FP_modules.1.mlp.layer1.normlayer.bn.bias", "module.pts_cam_extractor.FP_modules.1.mlp.layer1.normlayer.bn.running_mean", "module.pts_cam_extractor.FP_modules.1.mlp.layer1.normlayer.bn.running_var", "module.pts_cam_extractor.FP_modules.2.mlp.layer0.conv.weight", "module.pts_cam_extractor.FP_modules.2.mlp.layer0.normlayer.bn.weight", "module.pts_cam_extractor.FP_modules.2.mlp.layer0.normlayer.bn.bias", "module.pts_cam_extractor.FP_modules.2.mlp.layer0.normlayer.bn.running_mean", "module.pts_cam_extractor.FP_modules.2.mlp.layer0.normlayer.bn.running_var", "module.pts_cam_extractor.FP_modules.2.mlp.layer1.conv.weight", "module.pts_cam_extractor.FP_modules.2.mlp.layer1.normlayer.bn.weight", "module.pts_cam_extractor.FP_modules.2.mlp.layer1.normlayer.bn.bias", "module.pts_cam_extractor.FP_modules.2.mlp.layer1.normlayer.bn.running_mean", "module.pts_cam_extractor.FP_modules.2.mlp.layer1.normlayer.bn.running_var", "module.pts_cam_extractor.FP_modules.3.mlp.layer0.conv.weight", "module.pts_cam_extractor.FP_modules.3.mlp.layer0.normlayer.bn.weight", "module.pts_cam_extractor.FP_modules.3.mlp.layer0.normlayer.bn.bias", "module.pts_cam_extractor.FP_modules.3.mlp.layer0.normlayer.bn.running_mean", "module.pts_cam_extractor.FP_modules.3.mlp.layer0.normlayer.bn.running_var", "module.pts_cam_extractor.FP_modules.3.mlp.layer1.conv.weight", "module.pts_cam_extractor.FP_modules.3.mlp.layer1.normlayer.bn.weight", "module.pts_cam_extractor.FP_modules.3.mlp.layer1.normlayer.bn.bias", "module.pts_cam_extractor.FP_modules.3.mlp.layer1.normlayer.bn.running_mean", "module.pts_cam_extractor.FP_modules.3.mlp.layer1.normlayer.bn.running_var", "module.implicit_transform.feature_refine.pts_mlp1.0.weight", "module.implicit_transform.feature_refine.pts_mlp1.0.bias", "module.implicit_transform.feature_refine.pts_mlp1.2.weight", "module.implicit_transform.feature_refine.pts_mlp1.2.bias", "module.implicit_transform.feature_refine.deform_mlp1.0.weight", "module.implicit_transform.feature_refine.deform_mlp1.0.bias", "module.implicit_transform.feature_refine.deform_mlp1.2.weight", "module.implicit_transform.feature_refine.deform_mlp1.2.bias", "module.implicit_transform.feature_refine.deform_mlp2.0.weight", "module.implicit_transform.feature_refine.deform_mlp2.0.bias", "module.implicit_transform.feature_refine.deform_mlp2.2.weight", "module.implicit_transform.feature_refine.deform_mlp2.2.bias", "module.implicit_transform.feature_refine.deform_mlp2.4.weight", "module.implicit_transform.feature_refine.deform_mlp2.4.bias", "module.implicit_transform.feature_refine.pred_nocs.0.weight", "module.implicit_transform.feature_refine.pred_nocs.0.bias", "module.implicit_transform.feature_refine.pred_nocs.2.weight", "module.implicit_transform.feature_refine.pred_nocs.2.bias", "module.implicit_transform.feature_refine.pred_nocs.4.weight", "module.implicit_transform.feature_refine.pred_nocs.4.bias", "module.main_estimator.pts_mlp1.0.weight", "module.main_estimator.pts_mlp1.0.bias", "module.main_estimator.pts_mlp1.2.weight", "module.main_estimator.pts_mlp1.2.bias", "module.main_estimator.pts_mlp2.0.weight", "module.main_estimator.pts_mlp2.0.bias", "module.main_estimator.pts_mlp2.2.weight", "module.main_estimator.pts_mlp2.2.bias", "module.main_estimator.pose_mlp1.0.weight", "module.main_estimator.pose_mlp1.0.bias", "module.main_estimator.pose_mlp1.2.weight", "module.main_estimator.pose_mlp1.2.bias", "module.main_estimator.pose_mlp2.0.weight", "module.main_estimator.pose_mlp2.0.bias", "module.main_estimator.pose_mlp2.2.weight", "module.main_estimator.pose_mlp2.2.bias", "module.main_estimator.rotation_estimator.0.weight", "module.main_estimator.rotation_estimator.0.bias", "module.main_estimator.rotation_estimator.2.weight", "module.main_estimator.rotation_estimator.2.bias", "module.main_estimator.rotation_estimator.4.weight", "module.main_estimator.rotation_estimator.4.bias", "module.main_estimator.translation_estimator.0.weight", "module.main_estimator.translation_estimator.0.bias", "module.main_estimator.translation_estimator.2.weight", "module.main_estimator.translation_estimator.2.bias", "module.main_estimator.translation_estimator.4.weight", "module.main_estimator.translation_estimator.4.bias", "module.main_estimator.size_estimator.0.weight", "module.main_estimator.size_estimator.0.bias", "module.main_estimator.size_estimator.2.weight", "module.main_estimator.size_estimator.2.bias", "module.main_estimator.size_estimator.4.weight", "module.main_estimator.size_estimator.4.bias", "module.cam_enhancer.pts_mlp.0.weight", "module.cam_enhancer.pts_mlp.0.bias", "module.cam_enhancer.pts_mlp.2.weight", "module.cam_enhancer.pts_mlp.2.bias", "module.cam_enhancer.pose_mlp1.0.weight", "module.cam_enhancer.pose_mlp1.0.bias", "module.cam_enhancer.pose_mlp1.2.weight", "module.cam_enhancer.pose_mlp1.2.bias", "module.cam_enhancer.pose_mlp2.0.weight", "module.cam_enhancer.pose_mlp2.0.bias", "module.cam_enhancer.pose_mlp2.2.weight", "module.cam_enhancer.pose_mlp2.2.bias", "module.cam_enhancer.rotation_estimator.0.weight", "module.cam_enhancer.rotation_estimator.0.bias", "module.cam_enhancer.rotation_estimator.2.weight", "module.cam_enhancer.rotation_estimator.2.bias", "module.cam_enhancer.rotation_estimator.4.weight", "module.cam_enhancer.rotation_estimator.4.bias", "module.cam_enhancer.translation_estimator.0.weight", "module.cam_enhancer.translation_estimator.0.bias", "module.cam_enhancer.translation_estimator.2.weight", "module.cam_enhancer.translation_estimator.2.bias", "module.cam_enhancer.translation_estimator.4.weight", "module.cam_enhancer.translation_estimator.4.bias", "module.cam_enhancer.size_estimator.0.weight", "module.cam_enhancer.size_estimator.0.bias", "module.cam_enhancer.size_estimator.2.weight", "module.cam_enhancer.size_estimator.2.bias", "module.cam_enhancer.size_estimator.4.weight", "module.cam_enhancer.size_estimator.4.bias".

請問還需要修改什麼嗎？

**Comment by Eddieeee-Liu** [comment]
不好意思，这是一个bug。 我已经fix了，你可以重新pull一下代码尝试下

**Comment by corpse-dog** [comment]
似乎還是不行。
 See the documentation of nn.Upsample for details.
  "See the documentation of nn.Upsample for details.".format(mode)
Traceback (most recent call last):
  File "/data/jhq/IST-Net_new/train.py", line 191, in <module>
    Trainer.solve()
  File "/data/jhq/IST-Net_new/utils/solver.py", line 56, in solve
    dict_info_train = self.train()
  File "/data/jhq/IST-Net_new/utils/solver.py", line 95, in train
    loss, dict_info_step = self.step(syn_data, real_data, mode)
  File "/data/jhq/IST-Net_new/utils/solver.py", line 175, in step
    end_points = self.model(data)
  File "/home/ailab/.conda/envs/istnet/lib/python3.6/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/ailab/.conda/envs/istnet/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 168, in forward
    outputs = self.parallel_apply(replicas, inputs, kwargs)
  File "/home/ailab/.conda/envs/istnet/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 178, in parallel_apply
    return parallel_apply(replicas, inputs, kwargs, self.device_ids[:len(replicas)])
  File "/home/ailab/.conda/envs/istnet/lib/python3.6/site-packages/torch/nn/parallel/parallel_apply.py", line 86, in parallel_apply
    output.reraise()
  File "/home/ailab/.conda/envs/istnet/lib/python3.6/site-packages/torch/_utils.py", line 434, in reraise
    raise exception
TypeError: Caught TypeError in replica 0 on device 0.
Original Traceback (most recent call last):
  File "/home/ailab/.conda/envs/istnet/lib/python3.6/site-packages/torch/nn/parallel/parallel_apply.py", line 61, in _worker
    output = module(*input, **kwargs)
  File "/home/ailab/.conda/envs/istnet/lib/python3.6/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/data/jhq/IST-Net_new/model/ist_net.py", line 64, in forward
    end_points['pred_translation_aux_world'] = t_aux_world + c.squeeze(1)
TypeError: unsupported operand type(s) for +: 'NoneType' and 'Tensor'

**Comment by Eddieeee-Liu** [comment]
hello，因为之前整理代码的时候数据盘坏掉了，所以在本地没有做完整的测试，抱歉带来了这些问题，我又更新了一下，请再pull一下试试
