### ISSUE TITLE
Evaluation Metric

### ISSUE THREAD

**Issue by taeyeopl** [CVMI-Lab/IST-Net#6]
There exist small mistakes in the original evaluation source code of NOCS. I recommend changing to revised metrics (https://github.com/swords123/SSC-6D#note). DPDN code also has the same issues. 

https://github.com/CVMI-Lab/IST-Net/blob/169e1cf7ee2d2a56fdeee4a0d755b85df2330e7a/utils/evaluation_utils.py#L128-L131
```
        # new
        bbox_1_max = np.amax(bbox_3d_1, axis=1)
        bbox_1_min = np.amin(bbox_3d_1, axis=1)
        bbox_2_max = np.amax(bbox_3d_2, axis=1)
        bbox_2_min = np.amin(bbox_3d_2, axis=1)
```

**Comment by Eddieeee-Liu** [comment]
Thanks for your remind, I will update the code in the next few days!

**Comment by taeyeopl** [comment]
Thanks :)
